export const CREATE_BUSINESSTEMPLATE = "CREATE_BUSINESSTEMPLATE";
export const UPDATE_BUSINESSTEMPLATE = "UPDATE_BUSINESSTEMPLATE";
export const DELETE_BUSINESSTEMPLATE = "DELETE_BUSINESSTEMPLATE";
export const RETRIEVE_BUSINESSTEMPLATES = "RETRIEVE_BUSINESSTEMPLATES";
export const SET_BUSINESSTEMPLATE_PRICE_FILTER = "SET_BUSINESSTEMPLATE_PRICE_FILTER";

export const GET_BY_DEPARTMENTID = "GET_BY_DEPARTMENTID";
