export const CREATE_COMPARISON = "CREATE_COMPARISON";
export const UPDATE_COMPARISON = "UPDATE_COMPARISON";
export const DELETE_COMPARISON = "DELETE_COMPARISON";
export const RETRIEVE_COMPARISONS = "RETRIEVE_COMPARISONS";
export const SET_COMPARISON_PRICE_FILTER = "SET_COMPARISON_PRICE_FILTER";

// ComparisonItems
export const ADD_COMPARISONITEM = "ADD_COMPARISONITEM";
export const UPDATE_COMPARISONITEM = "UPDATE_COMPARISONITEM";
export const REMOVE_COMPARISONITEM = "REMOVE_COMPARISONITEM";
