export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const RETRIEVE_PRODUCTS = "RETRIEVE_PRODUCTS";
export const SET_PRODUCT_PRICE_FILTER = "SET_PRODUCT_PRICE_FILTER";

// Attributes
export const ADD_ATTRIBUTE = "ADD_ATTRIBUTE";
export const UPDATE_ATTRIBUTE = "UPDATE_ATTRIBUTE";
export const REMOVE_ATTRIBUTE = "REMOVE_ATTRIBUTE";
