export const CREATE_PURCHASEORDER = "CREATE_PURCHASEORDER";
export const UPDATE_PURCHASEORDER = "UPDATE_PURCHASEORDER";
export const DELETE_PURCHASEORDER = "DELETE_PURCHASEORDER";
export const RETRIEVE_PURCHASEORDERS = "RETRIEVE_PURCHASEORDERS";
export const SET_PURCHASEORDER_PRICE_FILTER = "SET_PURCHASEORDER_PRICE_FILTER";


// OrderLines
export const ADD_ORDERLINE = "ADD_ORDERLINE";
export const UPDATE_ORDERLINE = "UPDATE_ORDERLINE";
export const REMOVE_ORDERLINE = "REMOVE_ORDERLINE";
