export const CREATE_SELLER = "CREATE_SELLER";
export const UPDATE_SELLER = "UPDATE_SELLER";
export const DELETE_SELLER = "DELETE_SELLER";
export const RETRIEVE_SELLERS = "RETRIEVE_SELLERS";
export const SET_SELLER_PRICE_FILTER = "SET_SELLER_PRICE_FILTER";

export const GET_BY_DEPARTMENTID = "GET_BY_DEPARTMENTID";
