export const CREATE_COMMODITY = "CREATE_COMMODITY";
export const UPDATE_COMMODITY = "UPDATE_COMMODITY";
export const DELETE_COMMODITY = "DELETE_COMMODITY";
export const RETRIEVE_COMMODITIES = "RETRIEVE_COMMODITIES";
export const SET_COMMODITY_PRICE_FILTER = "SET_COMMODITY_PRICE_FILTER";

export const GET_BY_CATEGORYID = "GET_BY_CATEGORYID";

// Tags
export const ADD_TAG = "ADD_TAG";
export const UPDATE_TAG = "UPDATE_TAG";
export const REMOVE_TAG = "REMOVE_TAG";
// CommodityAttributes
export const ADD_COMMODITYATTRIBUTE = "ADD_COMMODITYATTRIBUTE";
export const UPDATE_COMMODITYATTRIBUTE = "UPDATE_COMMODITYATTRIBUTE";
export const REMOVE_COMMODITYATTRIBUTE = "REMOVE_COMMODITYATTRIBUTE";
