export const CREATE_REVIEW = "CREATE_REVIEW";
export const UPDATE_REVIEW = "UPDATE_REVIEW";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const RETRIEVE_REVIEWS = "RETRIEVE_REVIEWS";
export const SET_REVIEW_PRICE_FILTER = "SET_REVIEW_PRICE_FILTER";

export const GET_BY_REVIEWERID = "GET_BY_REVIEWERID";

// Comments
export const ADD_COMMENT = "ADD_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
