export const CREATE_ITEM = "CREATE_ITEM";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const RETRIEVE_ITEMS = "RETRIEVE_ITEMS";
export const SET_ITEM_PRICE_FILTER = "SET_ITEM_PRICE_FILTER";

// ItemPropertys
export const ADD_ITEMPROPERTY = "ADD_ITEMPROPERTY";
export const UPDATE_ITEMPROPERTY = "UPDATE_ITEMPROPERTY";
export const REMOVE_ITEMPROPERTY = "REMOVE_ITEMPROPERTY";
