export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const RETRIEVE_CATEGORIES = "RETRIEVE_CATEGORIES";
export const SET_CATEGORY_PRICE_FILTER = "SET_CATEGORY_PRICE_FILTER";

export const GET_BY_DEPARTMENTID = "GET_BY_DEPARTMENTID";
export const GET_BY_PARENTID = "GET_BY_PARENTID";
