export const CREATE_BUYER = "CREATE_BUYER";
export const UPDATE_BUYER = "UPDATE_BUYER";
export const DELETE_BUYER = "DELETE_BUYER";
export const RETRIEVE_BUYERS = "RETRIEVE_BUYERS";
export const SET_BUYER_PRICE_FILTER = "SET_BUYER_PRICE_FILTER";
