export const CREATE_BUYER = "CREATE_BUYER";
export const UPDATE_BUYER = "UPDATE_BUYER";
export const DELETE_BUYER = "DELETE_BUYER";
export const RETRIEVE_BUYERS = "RETRIEVE_BUYERS";
export const SET_BUYER_PRICE_FILTER = "SET_BUYER_PRICE_FILTER";


// Mamilas
export const ADD_MAMILA = "ADD_MAMILA";
export const UPDATE_MAMILA = "UPDATE_MAMILA";
export const REMOVE_MAMILA = "REMOVE_MAMILA";
// FavouriteItems
export const ADD_FAVOURITEITEM = "ADD_FAVOURITEITEM";
export const UPDATE_FAVOURITEITEM = "UPDATE_FAVOURITEITEM";
export const REMOVE_FAVOURITEITEM = "REMOVE_FAVOURITEITEM";
// Recommendations
export const ADD_RECOMMENDATION = "ADD_RECOMMENDATION";
export const UPDATE_RECOMMENDATION = "UPDATE_RECOMMENDATION";
export const REMOVE_RECOMMENDATION = "REMOVE_RECOMMENDATION";
