export const CREATE_CART = "CREATE_CART";
export const UPDATE_CART = "UPDATE_CART";
export const DELETE_CART = "DELETE_CART";
export const RETRIEVE_CARTS = "RETRIEVE_CARTS";
export const SET_CART_PRICE_FILTER = "SET_CART_PRICE_FILTER";

export const GET_BY_BUYERID = "GET_BY_BUYERID";

// CartLines
export const ADD_CARTLINE = "ADD_CARTLINE";
export const UPDATE_CARTLINE = "UPDATE_CARTLINE";
export const REMOVE_CARTLINE = "REMOVE_CARTLINE";
