export const CREATE_STORE = "CREATE_STORE";
export const UPDATE_STORE = "UPDATE_STORE";
export const DELETE_STORE = "DELETE_STORE";
export const RETRIEVE_STORES = "RETRIEVE_STORES";
export const SET_STORE_PRICE_FILTER = "SET_STORE_PRICE_FILTER";


// BussinessHours
export const ADD_BUSSINESSHOUR = "ADD_BUSSINESSHOUR";
export const UPDATE_BUSSINESSHOUR = "UPDATE_BUSSINESSHOUR";
export const REMOVE_BUSSINESSHOUR = "REMOVE_BUSSINESSHOUR";
