export const CREATE_DEPARTMENT = "CREATE_DEPARTMENT";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
export const RETRIEVE_DEPARTMENTS = "RETRIEVE_DEPARTMENTS";
export const SET_DEPARTMENT_PRICE_FILTER = "SET_DEPARTMENT_PRICE_FILTER";
